version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install

  build:
    commands:
      - pnpm build
      - pnpm export
      - echo "📂 Built files:"
      - ls -al

artifacts:
  base-directory: out
  files:
    - '**/*'
