version: 0.1

phases:
  install:
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - pnpm run build  # Builds the project
      - aws cloudfront create-invalidation --distribution-id E2KOZZQHUQI9Q2 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: out  # Directory with output files (e.g., React app)